blank_issues_enabled: true
contact_links:
  - name: Oficiální Discord
    url: https://discord.gg/resonite
    about: Místo, kde se diskutuje o všem, co se týká Resonite.
  - name: Resonite moderace
    url: https://moderation.resonite.com
    about: Jakékoli porušení pokynů prosím nahlaste zde.
  - name: Resonite podpora
    url: https://support.resonite.com
    about: Jakékoli problémy s účtem prosím nahlaste zde.
  - name: Bezpečnost
    url: https://support.resonite.com
    about: Jakékoli bezpečnostní problémy prosím nahlaste zde.
  - name: Chyby a požadavky na nové funkce
    url: https://github.com/Yellow-Dog-Man/Resonite-Issues
    about: Chyby a návrhy na nové funkce zasílejte sem.
